### ISSUE TITLE
Cran Documentation Gone

### ISSUE THREAD

**Issue by chrisbeckett8** [waddella/loon#5]
I was trying to look up the cran documentation online and it said that loon is now archived. Is this true?

**Comment by waddella** [comment]
Unfortunately I have failed to address an issue in time and the package has been archived on CRAN a couple of days ago. I will try to fix the issue and resubmit the package tomorrow.

Sorry for the inconvenience.

**Comment by chrisbeckett8** [comment]
No problem. I am creating a visualization tool using your package for my
Master's thesis so I was worried it might become a deprecated package. So,
thank you a million for creating the package and keeping it up to date. My
work wouldn't be possible without yours.

I am creating a layout of 4 plots that almost fills the screen. Is there a
way to attach the loon inspector to the same screen as the graphs so I
don't have to click back and forth between them?

**Comment by waddella** [comment]
Hi @chrisbeckett8,

Loon is now on CRAN again. I am happy loon is useful for you. It would be great to see your work, if you can share it.

Regarding placing the loon inspector at a custom place, have a look at the `l_widgets` demo:

https://github.com/waddella/loon/blob/master/R/demo/l_widgets.R

Best,
Adrian

**Comment by chrisbeckett8** [comment]
Adrian,
I would love to share what I am doing for my work, but since I am going to
be writing a paper on it, I will share the completed product when it is
done.. It relies heavily on your package, so thank you again.

Thank you for the info about placing the loon inspector at a custom place.
Another question I have, is there a way I can do a 3d scatter plot, where I
can rotate it on its axis and see the different sides, like with rgl? Also,
have you ever embedded loon into shiny?

Thank you,
Chris
