### ISSUE TITLE
Highlight Color is pink

### ISSUE THREAD

**Issue by chrisbeckett8** [waddella/loon#7]
Hello,
I can easily see how to change the color palette for plots. How do we change the default 'selected' color from pink for when I select certain points on a plot? I have looked through the documentation but have not found anything.

**Comment by waddella** [comment]
Hi @chrisbeckett8,

I have currently not exposed that option in `R`. However you can do it with:

```r
library(loon)

tcl('set', '::loon::Options(select-color)', 'green')

p <- l_plot(iris)
```
